### ISSUE TITLE
Behaviour of partial

### ISSUE THREAD

**Issue by sylvainbonnot** [i2mint/meshed#4]
As of now, the partial method returns the correct result, and the correct visualization as well, except that the bound arguments still show up. But here are some question we need to consider: Now you want to obfuscate the bound arguments, but:

- You might have had defaulted arguments before, do you obfuscate those by default? (I say no, because it's the conservative way -- some may be None or sentinels that lead to defaults or not etc.)
- If you choose to obfuscate (by default or not -- I say not, for now) bound arguments, do you still leave orphaned funcnodes (just without arguments), or do you "roll them in" (here we'd be left with confusion_value -> classifier_score_ -> classifier_score only.

**Comment by thorwhalen** [comment]
Partial has now a working `_remove_bound_arguments`. Set default to `False`. 

I have placeholder code for `_roll_in_orphaned_nodes`, but needs to be implemented.

**Comment by thorwhalen** [comment]
Also needed:

* tests and doctests
* thinking, testing, and handling the case where partialized arguments might have been bound with a different name

@cavart28 and/or @sylvainbonnot , want to pick this up?

**Comment by thorwhalen** [comment]
I'm going to remove the ``_roll_in_orphaned_nodes=False`` argument for now.

See https://github.com/i2mint/meshed/issues/14 for further information.
